/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as PublicFormsRouteImport } from './routes/_publicForms.tsx'
import { Route as PublicRouteImport } from './routes/_public.tsx'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated.tsx'
import { Route as PublicIndexRouteImport } from './routes/_public/index.tsx'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route.tsx'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index.tsx'
import { Route as PublicFormsAuthResetPasswordRouteImport } from './routes/_publicForms/auth/reset-password.tsx'
import { Route as PublicFormsAuthLoginRouteImport } from './routes/_publicForms/auth/login.tsx'
import { Route as PublicFormsAuthBootstrapRouteImport } from './routes/_publicForms/auth/bootstrap.tsx'
import { Route as PublicFormsAuthAcceptInviteRouteImport } from './routes/_publicForms/auth/accept-invite.tsx'
import { Route as AuthenticatedDashboardProfileIndexRouteImport } from './routes/_authenticated/dashboard/profile/index.tsx'
import { Route as AuthenticatedDashboardCardIdIndexRouteImport } from './routes/_authenticated/dashboard/$cardId/index.tsx'
import { Route as AuthenticatedFormsOnboardingIndexRouteImport } from './routes/_authenticated/_forms/onboarding/index.tsx'
import { Route as AuthenticatedFormsAuthInviteRouteImport } from './routes/_authenticated/_forms/auth/invite.tsx'

const PublicFormsRoute = PublicFormsRouteImport.update({
  id: '/_publicForms',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const PublicFormsAuthResetPasswordRoute =
  PublicFormsAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => PublicFormsRoute,
  } as any)
const PublicFormsAuthLoginRoute = PublicFormsAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicFormsRoute,
} as any)
const PublicFormsAuthBootstrapRoute =
  PublicFormsAuthBootstrapRouteImport.update({
    id: '/auth/bootstrap',
    path: '/auth/bootstrap',
    getParentRoute: () => PublicFormsRoute,
  } as any)
const PublicFormsAuthAcceptInviteRoute =
  PublicFormsAuthAcceptInviteRouteImport.update({
    id: '/auth/accept-invite',
    path: '/auth/accept-invite',
    getParentRoute: () => PublicFormsRoute,
  } as any)
const AuthenticatedDashboardProfileIndexRoute =
  AuthenticatedDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCardIdIndexRoute =
  AuthenticatedDashboardCardIdIndexRouteImport.update({
    id: '/$cardId/',
    path: '/$cardId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedFormsOnboardingIndexRoute =
  AuthenticatedFormsOnboardingIndexRouteImport.update({
    id: '/_forms/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormsAuthInviteRoute =
  AuthenticatedFormsAuthInviteRouteImport.update({
    id: '/_forms/auth/invite',
    path: '/auth/invite',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/auth/accept-invite': typeof PublicFormsAuthAcceptInviteRoute
  '/auth/bootstrap': typeof PublicFormsAuthBootstrapRoute
  '/auth/login': typeof PublicFormsAuthLoginRoute
  '/auth/reset-password': typeof PublicFormsAuthResetPasswordRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/auth/invite': typeof AuthenticatedFormsAuthInviteRoute
  '/onboarding': typeof AuthenticatedFormsOnboardingIndexRoute
  '/dashboard/$cardId': typeof AuthenticatedDashboardCardIdIndexRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth/accept-invite': typeof PublicFormsAuthAcceptInviteRoute
  '/auth/bootstrap': typeof PublicFormsAuthBootstrapRoute
  '/auth/login': typeof PublicFormsAuthLoginRoute
  '/auth/reset-password': typeof PublicFormsAuthResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/auth/invite': typeof AuthenticatedFormsAuthInviteRoute
  '/onboarding': typeof AuthenticatedFormsOnboardingIndexRoute
  '/dashboard/$cardId': typeof AuthenticatedDashboardCardIdIndexRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_publicForms': typeof PublicFormsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_publicForms/auth/accept-invite': typeof PublicFormsAuthAcceptInviteRoute
  '/_publicForms/auth/bootstrap': typeof PublicFormsAuthBootstrapRoute
  '/_publicForms/auth/login': typeof PublicFormsAuthLoginRoute
  '/_publicForms/auth/reset-password': typeof PublicFormsAuthResetPasswordRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_forms/auth/invite': typeof AuthenticatedFormsAuthInviteRoute
  '/_authenticated/_forms/onboarding/': typeof AuthenticatedFormsOnboardingIndexRoute
  '/_authenticated/dashboard/$cardId/': typeof AuthenticatedDashboardCardIdIndexRoute
  '/_authenticated/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/auth/accept-invite'
    | '/auth/bootstrap'
    | '/auth/login'
    | '/auth/reset-password'
    | '/dashboard/'
    | '/auth/invite'
    | '/onboarding'
    | '/dashboard/$cardId'
    | '/dashboard/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/accept-invite'
    | '/auth/bootstrap'
    | '/auth/login'
    | '/auth/reset-password'
    | '/dashboard'
    | '/auth/invite'
    | '/onboarding'
    | '/dashboard/$cardId'
    | '/dashboard/profile'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_publicForms'
    | '/_authenticated/dashboard'
    | '/_public/'
    | '/_publicForms/auth/accept-invite'
    | '/_publicForms/auth/bootstrap'
    | '/_publicForms/auth/login'
    | '/_publicForms/auth/reset-password'
    | '/_authenticated/dashboard/'
    | '/_authenticated/_forms/auth/invite'
    | '/_authenticated/_forms/onboarding/'
    | '/_authenticated/dashboard/$cardId/'
    | '/_authenticated/dashboard/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  PublicFormsRoute: typeof PublicFormsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_publicForms': {
      id: '/_publicForms'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_publicForms/auth/reset-password': {
      id: '/_publicForms/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof PublicFormsAuthResetPasswordRouteImport
      parentRoute: typeof PublicFormsRoute
    }
    '/_publicForms/auth/login': {
      id: '/_publicForms/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicFormsAuthLoginRouteImport
      parentRoute: typeof PublicFormsRoute
    }
    '/_publicForms/auth/bootstrap': {
      id: '/_publicForms/auth/bootstrap'
      path: '/auth/bootstrap'
      fullPath: '/auth/bootstrap'
      preLoaderRoute: typeof PublicFormsAuthBootstrapRouteImport
      parentRoute: typeof PublicFormsRoute
    }
    '/_publicForms/auth/accept-invite': {
      id: '/_publicForms/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof PublicFormsAuthAcceptInviteRouteImport
      parentRoute: typeof PublicFormsRoute
    }
    '/_authenticated/dashboard/profile/': {
      id: '/_authenticated/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/$cardId/': {
      id: '/_authenticated/dashboard/$cardId/'
      path: '/$cardId'
      fullPath: '/dashboard/$cardId'
      preLoaderRoute: typeof AuthenticatedDashboardCardIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/_forms/onboarding/': {
      id: '/_authenticated/_forms/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedFormsOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_forms/auth/invite': {
      id: '/_authenticated/_forms/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthenticatedFormsAuthInviteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCardIdIndexRoute: typeof AuthenticatedDashboardCardIdIndexRoute
  AuthenticatedDashboardProfileIndexRoute: typeof AuthenticatedDashboardProfileIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCardIdIndexRoute:
      AuthenticatedDashboardCardIdIndexRoute,
    AuthenticatedDashboardProfileIndexRoute:
      AuthenticatedDashboardProfileIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedFormsAuthInviteRoute: typeof AuthenticatedFormsAuthInviteRoute
  AuthenticatedFormsOnboardingIndexRoute: typeof AuthenticatedFormsOnboardingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedFormsAuthInviteRoute: AuthenticatedFormsAuthInviteRoute,
  AuthenticatedFormsOnboardingIndexRoute:
    AuthenticatedFormsOnboardingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface PublicFormsRouteChildren {
  PublicFormsAuthAcceptInviteRoute: typeof PublicFormsAuthAcceptInviteRoute
  PublicFormsAuthBootstrapRoute: typeof PublicFormsAuthBootstrapRoute
  PublicFormsAuthLoginRoute: typeof PublicFormsAuthLoginRoute
  PublicFormsAuthResetPasswordRoute: typeof PublicFormsAuthResetPasswordRoute
}

const PublicFormsRouteChildren: PublicFormsRouteChildren = {
  PublicFormsAuthAcceptInviteRoute: PublicFormsAuthAcceptInviteRoute,
  PublicFormsAuthBootstrapRoute: PublicFormsAuthBootstrapRoute,
  PublicFormsAuthLoginRoute: PublicFormsAuthLoginRoute,
  PublicFormsAuthResetPasswordRoute: PublicFormsAuthResetPasswordRoute,
}

const PublicFormsRouteWithChildren = PublicFormsRoute._addFileChildren(
  PublicFormsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  PublicFormsRoute: PublicFormsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
